#!/bin/bash
#
# Generate one cellranger multi run per sequencing pool.
#
# Everything comes from config/config.env and config/samples.tsv: the pools,
# the fastq prefixes, the hashtag-to-sample assignments, the library types and
# the SLURM settings. You should not need to edit this script.
#
# For each pool it writes:
#     <POOL>_run/multi_config_<POOL>.csv    the cellranger multi config
#     <POOL>_run/cellranger_<POOL>.sbatch   the job script
#     <POOL>_run/logs/                      where job output lands
#
# Run:
#     bash 03_make_per_pool_runs.bash
#
# Then submit everything with:
#     bash 04_submit_all.bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../config/load_config.bash"
check_config

# ---- reference paths (must match what 02_make_refs.bash downloaded) ---------
case "$SPECIES" in
  mouse)
    REF_GEX="${SCRIPT_DIR}/refs/refdata-gex-GRCm39-2024-A"
    REF_VDJ="${SCRIPT_DIR}/refs/refdata-cellranger-vdj-GRCm38-alts-ensembl-7.0.0"
    ;;
  human)
    REF_GEX="${SCRIPT_DIR}/refs/refdata-gex-GRCh38-2024-A"
    REF_VDJ="${SCRIPT_DIR}/refs/refdata-cellranger-vdj-GRCh38-alts-ensembl-7.1.0"
    ;;
esac

FEATURE_REF="${SCRIPT_DIR}/refs/feature_ref.csv"
GEX_FQ="${SCRIPT_DIR}/symlinks/gex_fastqs"
CSP_FQ="${SCRIPT_DIR}/symlinks/csp_fastqs"
TCR_FQ="${SCRIPT_DIR}/symlinks/vdjt_fastqs"
BCR_FQ="${SCRIPT_DIR}/symlinks/vdjb_fastqs"

# ---- sanity checks -----------------------------------------------------------
if [ ! -d "$REF_GEX" ]; then
  echo "ERROR: GEX reference not found: $REF_GEX" >&2
  echo "       Run 'bash 02_make_refs.bash' first." >&2
  exit 1
fi

if has_library TCR || has_library BCR; then
  if [ ! -d "$REF_VDJ" ]; then
    echo "ERROR: VDJ reference not found: $REF_VDJ" >&2
    echo "       Run 'bash 02_make_refs.bash' first." >&2
    exit 1
  fi
fi

if has_library CSP && [ ! -f "$FEATURE_REF" ]; then
  echo "ERROR: feature reference not found: $FEATURE_REF" >&2
  exit 1
fi

if [ ! -d "$GEX_FQ" ]; then
  echo "ERROR: fastq symlinks not found: $GEX_FQ" >&2
  echo "       Run 'bash 01_make_symlinks.bash' first." >&2
  exit 1
fi

POOLS="$(sample_pools)"
if [ -z "$POOLS" ]; then
  echo "ERROR: no pools found in ${SAMPLES_TSV}" >&2
  exit 1
fi

echo "Species:  $SPECIES"
echo "Libraries: $LIBRARY_TYPES"
echo "Hashtag demux: ${USE_HASHTAG_DEMUX}"
echo

# ---- generate one run per pool ----------------------------------------------
for POOL in $POOLS; do
  pfx="$(pool_prefix "$POOL")"
  if [ -z "$pfx" ]; then
    echo "ERROR: no pool_prefix for pool '${POOL}' in ${SAMPLES_TSV}" >&2
    exit 1
  fi

  run="${SCRIPT_DIR}/${POOL}_run"
  mkdir -p "${run}/logs"

  cfg="${run}/multi_config_${POOL}.csv"

  {
    echo "[gene-expression]"
    echo "reference,${REF_GEX}"
    echo "create-bam,${CREATE_BAM:-false}"
    echo

    if has_library TCR || has_library BCR; then
      echo "[vdj]"
      echo "reference,${REF_VDJ}"
      echo
    fi

    if has_library CSP; then
      echo "[feature]"
      echo "reference,${FEATURE_REF}"
      echo
    fi

    echo "[libraries]"
    echo "fastq_id,fastqs,feature_types,physical_library_id"
    echo "${pfx}-GEX,${GEX_FQ},Gene Expression,GEX"
    has_library CSP && echo "${pfx}-CSP,${CSP_FQ},Antibody Capture,CSP"
    has_library TCR && echo "${pfx}-TCR,${TCR_FQ},VDJ-T,TCR"
    has_library BCR && echo "${pfx}-BCR,${BCR_FQ},VDJ-B,BCR"

    # The [samples] section tells Cell Ranger how to split a pooled run back
    # into individual specimens using hashtags. Omit it entirely when the run
    # is not multiplexed.
    if [ "${USE_HASHTAG_DEMUX:-false}" = "true" ]; then
      echo
      echo "[samples]"
      echo "sample_id,hashtag_ids"
      samples_data | awk -F'\t' -v p="$POOL" '$1==p {print $4","$3}'
    fi
  } > "$cfg"

  n_samples=$(samples_data | awk -F'\t' -v p="$POOL" '$1==p' | wc -l | tr -d ' ')

  # ---- job script ----
  cat > "${run}/cellranger_${POOL}.sbatch" << EOF
#!/bin/bash
#SBATCH --job-name=${POOL}_cellranger
#SBATCH --output=logs/cellranger_${POOL}.%j.out
#SBATCH --error=logs/cellranger_${POOL}.%j.err
#SBATCH --qos=${SLURM_QOS}
#SBATCH --account=${SLURM_ACCOUNT}
#SBATCH --time=${CELLRANGER_TIME:-24:00:00}
#SBATCH --mem=${CELLRANGER_MEM:-250G}
#SBATCH --cpus-per-task=${CELLRANGER_CPUS:-32}

# Generated by 03_make_per_pool_runs.bash - do not edit by hand.
# Re-run that script to regenerate after changing config/ files.

set -euo pipefail

cd \${SLURM_SUBMIT_DIR}

$(if [ "${USE_MODULES:-true}" = "true" ]; then echo "module load ${CELLRANGER_MODULE:-cellranger/9.0.0}"; fi)
export TENX_IGNORE_DEPRECATED_OS=1

cellranger multi \\
    --id=${POOL}_multi \\
    --csv=multi_config_${POOL}.csv \\
    --localcores=\${SLURM_CPUS_PER_TASK} \\
    --localmem=\$(( \${SLURM_MEM_PER_NODE} / 1024 ))
EOF

  echo "  ${POOL}: ${cfg}  (prefix ${pfx}, ${n_samples} samples)"
done

echo
echo "Review one of the generated configs before submitting, e.g.:"
echo "  cat $(echo "$POOLS" | head -1)_run/multi_config_$(echo "$POOLS" | head -1).csv"
echo
echo "Then submit all pools with:  bash 04_submit_all.bash"
